/**
 * Copyright (c) 2026. Cloud Software Group, Inc. All Rights Reserved. Confidential & Proprietary
 */

package com.tibco.xpd.n2.gat.generation;

import java.util.Collection;

import com.tibco.xpd.n2.gat.model.GatCollaborationElement;
import com.tibco.xpd.n2.gat.model.GatParticipantElement;
import com.tibco.xpd.xpdl2.Pool;
import com.tibco.xpd.xpdl2.Process;
import com.tibco.xpd.n2.gat.util.GatModelUtil;

/**
 * Graphical Audit Trail generator for the CollaborATION model element.
 *
 * @author Sid Allway
 * @since 23 Mar 2026
 */
@SuppressWarnings("nls")
public class GatCollaborationGenerator extends BaseGatGenerator
{
	/**
	 * The XPDL process for this collaboration
	 */
	private Process					xpdlProcess;

	/**
	 * The {@link GatCollaborationElement} generated by {@link #generate()}
	 */
	private GatCollaborationElement	collaborationElement	= null;

	/**
	 * The {@link GatParticipantElement} generated by {@link #generate()} if XPDL process has a Pool
	 */
	private GatParticipantElement	participantElement		= null;

	/**
	 * @param parent
	 */
	public GatCollaborationGenerator(BaseGatGenerator parent, Process xpdlProcess)
	{
		super(parent);
		this.xpdlProcess = xpdlProcess;
	}

	/**
	 * @see com.tibco.xpd.n2.gat.generation.BaseGatGenerator#generate()
	 *
	 * @return
	 */
	@Override
	public GatCollaborationElement generate()
	{
		/* Create the collaboration element */
		collaborationElement = new GatCollaborationElement(xpdlProcess.getId() + "_collaboration");

		/*
		 * Add the pool for the process we're dealing with.
		 *
		 * In BPMN there is also actually a one-to-one relationship between a Pool (if there is one) and a process. The
		 * activities in the lanes in a given pool are all contained within a single process. In Studio process molder
		 * it is different, it behaves (probably incorrectly) like a process can contain multiple pools.
		 *
		 * But we don't need to worry about that, because XPDL processes with multiple pools are not deployable in BPMe
		 * / AMX BPM. So there is effectively a 1-2-1 relationship by the time the process can be deployed.
		 */
		Collection<Pool> pools = GatModelUtil.getProcessPools(xpdlProcess);

		if (pools.size() > 1)
		{
			throw new RuntimeException("Graphical Audit Trail models do not support profecsses with multiple pools.");
		}

		/*
		 * We'll allow no pools at all, just in case we ever allow that in proess modeller (as it doesnt' make sense
		 * these (and business services don't have them for example)
		 */
		if (pools.size() == 1)
		{
			/*
			 * Add a participant to represent the pool
			 */
			Pool pool = pools.iterator().next();

			participantElement = new GatParticipantElement(pool.getId(), pool.getName(),
					GatModelUtil.getDisplayNameOrName(pool));

			participantElement.setProcessRef(xpdlProcess.getId());

			collaborationElement.addParticipantElement(participantElement);
		}

		return collaborationElement;
	}

	/**
	 * If the XPDL process had a Pool, the a GAT participant will have been generated by {@link #generate()}
	 *
	 *
	 * @return {@link GatParticipantElement} or <code>null</code>if xpdlProcess hasn't got a Pool or {@link #generate()}
	 *         not called yet
	 */
	public GatParticipantElement getParticipant()
	{
		return participantElement;
	}
}
